#!/bin/bash

all: test

test:
	python lasso_regression_params.py
	python logistic_regression_params.py
	python naive_cnn_params.py
	python defossez2022decoding_params.py

clean:
	rm -rf ./__pycache__

